networks:
  public_net:
    external: true

volumes:
  xel_db:

services:
  api:
    image: ghcr.io/julioguirola/xelemetry:latest
    networks:
      - public_net
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=public_net"
        - "traefik.http.routers.xelemetry.rule=Host(`xel.tramitsdevs.tech`)"
        - "traefik.http.routers.xelemetry.entrypoints=websecure"
        - "traefik.http.routers.xelemetry.tls=true"
        - "traefik.http.routers.xelemetry.tls.certresolver=myresolver"
        - "traefik.http.services.xelemetry-svc.loadbalancer.server.port=1323"
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
        reservations:
          cpus: "0.05"
          memory: 64M
    restart: always
    volumes:
      - xel_db:/data
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - TELEGRAM_MESSAGE_THREAD_ID=${TELEGRAM_MESSAGE_THREAD_ID}
      - DB_PATH=/data/checks.db

  # daemon:
  #   image: ghcr.io/julioguirola/xelemetry:latest
  #   restart: always
  #   environment:
  #     - API_URL=${API_URL}
  #     - LOCATION_ID=${LOCATION_ID}
  #   command: ./app
